url: https://mendelbrot.github.io
description: My hobbies and projects site
author: Gregory Maxedon
about: |
  This blog is mainly for featuring portfolio projects and posts about software development.  I also use this blog for anything else I feel like posting.  
nav:
  - path: / 
    label: Home
  - path: /posts/
    label: Posts
  - path: /about/
    label: About