url: https://mendelbrot.github.io
description: My hobbies and projects site
author: Gregory Maxedon
about: |
  this blog is mainly for featuring portfolio projects and posts about software development.  it's existence is an incentive for me to create content for it.  i also use this blog for anything else i feel like posting.  so far, it's a mix of posts about web development, and posts about random fringe hobbies.
nav:
  - path: / 
    label: Home
  - path: /posts/
    label: Posts
  - path: /about/
    label: About