mindmap
  root((documentation))
    process
      work notes
      code comments
      meeting notes
    product
      readme
        title
        description
        install / run / deploy
        use / use examples
      system documentation
        modules
        sequence diagram
        api documentation
        database erd

