contact:
  name: Greg Maxedon
  location: Vancouver, BC
  phone: 604-700-6241
  email: gregory.maxedon@gmail.com
  website: https://mendelbrot.github.io
  linkedin: https://linkedin.com/in/gregmaxedon/
  github: https://github.com/mendelbrot

skills:
  - JavaScript
  - TypeScript
  - Python
  - Elixir
  - Rust
  - Tailwind CSS
  - React
  - NodeJS
  - REST APIs
  - GraphQL
  - Database design
  - PostgreSQL
  - MongoDB
  - Git
  - Linux
  - Bash
  - AWS
  - Docker

education:
  - school: British Columbia Institute of Technology
    program: Software Systems Developer Certificate
    dates: 2018 - 2019
    location: Vancouver, BC
    grade: A+

  - school: Simon Fraser University
    program: Bachelor of Science in Physics
    dates: 2008 - 2015
    location: Burnaby, BC
    grade: A-

experience:
  - company: MistyWest
    role: IT Automation Developer (Part Time)
    dates: May 2021 - Present
    location: Vancouver, BC
    achievements:
      - Offered IT support, addressing hardware and software issues.
      - Developed a full-stack web application and created automation scripts using Python and JavaScript.
      - Conducted computer and server repairs and performed system upgrades.
      - Acted as an administrator for Salesforce, Microsoft Active Directory, Google Workspace, and other SaaS platforms.
  
  - company: Plasmatic Technologies
    role: Frontend Developer
    dates: Jun 2019 - Mar 2020
    location: Vancouver, BC
    achievements:
      - Developed a React dashboard web application for use by business customers.
      - Collaborated on NodeJS lambda functions and GraphQL APIs.
      - Worked with AWS services, including Lambda, Cognito, DynamoDB, and S3.

  - company: Ballard Power Systems
    role: Production Technician
    dates: Mar 2016 - Dec 2016
    location: Burnaby, BC
    achievements:
      - Produced components with care and attention that met stringent quality standards.
      - Followed workmanship guidelines and written instructions.
      - Operated manufacturing equipment while adhering to safety protocols.
  
  - company: ALS Environmental
    role: Laboratory Assistant
    dates: Jul 2009 - Dec 2012
    location: Burnaby, BC
    achievements:
      - > 
        Conducted water sample tests for parameters including: turbidity, colour, pH, TSS, TDS, VOC
      - Entered test results data into computer systems.
      - Operated and monitored automated testing equipment.
      - Ensured the cleanliness and proper upkeep of laboratory equipment, including washing lab apparatus.
      - Performed sample logistics and sample preservation with HCl and H<sub>2</sub>SO<sub>4</sub>.