contact:
  name: Greg Maxedon
  title: Web Developer
  location: Vancouver, British Columbia, Canada
  phone: 
  email:
  website: https://mendelbrot.github.io
  linkedin: https://www.linkedin.com/in/gregmaxedon/
  github: https://github.com/mendelbrot

summary: |
  this blog is mainly for featuring portfolio projects and posts about software development.  it's existence is an incentive for me to create content for it.  i also use this blog for anything else i feel like posting.  so far, it's a mix of posts about web development, and posts about random fringe hobbies.

skills:
  - JavaScript
  - TypeScript
  - Python
  - Elixir
  - Rust
  - Tailwind CSS
  - React
  - NodeJS
  - REST APIs
  - GraphQL
  - Database design
  - PostgreSQL
  - MongoDB
  - Git
  - Linux
  - Bash
  - AWS

education:
  - school: British Columbia Institute of Technology
    program: Software Systems Developer Certificate
    dates: Sep 2018 - Jun 2019
    grade: 96%

  - school: Simon Fraser University
    program: Bachelor of Science in Physics
    dates: Sep 2008 - Jun 2015
    grade: 3.70/4.33

experience:
  - company: MistyWest
    role: IT Automation Developer (Part Time)
    dates: May 2021 - Present (2 years)
    location: Vancouver, British Columbia, Canada
    achievements:
      - Built a full-stack web application used by around ten people
      - Created automation scripts with Python
      - Helped to set up and maintain the network and servers
      - Salesforce Admin and Developer
      - Admin for Microsoft Active Directory, Google Workspace, and other SaaS
      - Provided IT support with hardware and software troubleshooting