name: Eleventy Build

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3

        - name: Install latest mdbook
          run: |
            tag=$(curl 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
            url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
            mkdir mdbook
            curl -sSL $url | tar -xz --directory=./mdbook
            echo `pwd`/mdbook >> $GITHUB_PATH

        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: '16.x'

        - name: install node modules
          run: npm ci

        - name: globally install mermaid
          run: npm install -g @mermaid-js/mermaid-cli

        - name: build the .mmd images for the mdbook docs
          run: npm run mermaid

        - name: build the mdbook docs
          run: npm run docs

        - name: build the 11ty static site
          run: npm run build

        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
            publish_dir: ./_site